# Generated by Django 4.2 on 2023-04-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreport',
            name='employee_name',
            field=models.CharField(default='No Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='report_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
