# Generated by Django 4.2 on 2023-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPSapp', '0002_summaryreport_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryreport',
            name='prod_score',
            field=models.FloatField(),
        ),
    ]
