# Generated by Django 4.0.4 on 2023-04-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('employee_fname', models.CharField(max_length=255)),
                ('employee_mname', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_lname', models.CharField(max_length=255)),
                ('employee_sex', models.CharField(max_length=1)),
                ('employee_bday', models.DateField()),
                ('employee_email', models.CharField(max_length=255)),
                ('employee_num', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_emergnum', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('history_no', models.CharField(max_length=10)),
                ('position_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('report_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prod_date', models.DateField()),
                ('workinghours', models.DurationField()),
                ('remarks', models.TextField(blank=True, max_length=2000)),
                ('prod_score', models.FloatField(null=True)),
                ('joborder_no', models.CharField(max_length=10)),
                ('process', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProdDB.employee')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('employee_fname', models.CharField(max_length=255)),
                ('employee_mname', models.CharField(blank=True, max_length=255)),
                ('employee_lname', models.CharField(max_length=255)),
                ('position_name', models.CharField(max_length=255)),
                ('position_startdate', models.DateField()),
                ('position_enddate', models.DateField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProdDB.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProdDB.position')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('report_no', models.CharField(max_length=255)),
                ('timespan', models.DurationField()),
                ('displaytype', models.CharField(max_length=255)),
                ('total_workinghours', models.DurationField()),
                ('contribution', models.CharField(max_length=10)),
                ('avgprodscore', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProdDB.employee')),
            ],
        ),
    ]
