# Generated by Django 4.0.4 on 2023-04-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProdDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivity',
            name='employee',
        ),
        migrations.AlterField(
            model_name='productivity',
            name='prod_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='report_no',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
